name: Playwright Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run playwright extension tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Install playwright chromium
        run: yarn playwright install chromium

      - name: Run tests
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
